"""empty message

Revision ID: 79c5804bdb08
Revises: 
Create Date: 2020-01-20 21:56:48.259067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c5804bdb08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('goal', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
