"""empty message

Revision ID: d7b44144953a
Revises: 
Create Date: 2020-01-24 22:02:46.980434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b44144953a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('hour', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'teacher_id')
    op.drop_column('bookings', 'hour')
    op.drop_column('bookings', 'day')
    # ### end Alembic commands ###
